name: Deploy subfolder to GH Actions
on:
  push:
    branches: [ "master" ]
    paths:
      - 'src/**'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Delete husky
        run: npm pkg delete scripts.prepare --force

      - name: Install deps
        run: npm ci --force

      - name: Gulp build
        run: npm run build

      - name: Commit builded files
        run: |
          git config --local user.name  ${{ github.actor }}
          git config --local user.email "polaris9955@gmail.com"
          git add -A
          git commit -m "build: update gulp output files"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          # force: true

  deploy:
    name: Place subfolder to deploy branch
    needs: [build]
    runs-on: ubuntu-latest
    steps:

    # Any prerequisite steps
    - name: Checkout
      uses: actions/checkout@master

    - name: Increase Git buffer
      run: |
        git config --global http.postBuffer 157286400

    # Deploy to local repo
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: deploy/gh-pages
        FOLDER: prod
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
